// src/app/reset-password/page.tsx
"use client";

import { useSearchParams } from "next/navigation";
import { useState } from "react";

export default function ResetPasswordPage() {
  const searchParams = useSearchParams();
  const token = searchParams.get("token");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [error, setError] = useState("");
  const [success, setSuccess] = useState(false);
  const [loading, setLoading] = useState(false);

  async function handleSubmit(event: React.FormEvent) {
    event.preventDefault();
    setError("");

    if (password !== confirmPassword) {
      setError("Passwords do not match");
      return;
    }

    setLoading(true);
    try {
      const response = await fetch("/api/auth/reset-password", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ token, password }),
      });
      const data = await response.json();
      if (!response.ok) setError(data.error);
      else setSuccess(true);
    } catch {
      setError("Something went wrong. Please try again.");
    } finally {
      setLoading(false);
    }
  }

  if (!token) {
    return (
      <div className="flex min-h-screen items-center justify-center">
        <p className="text-[var(--text-muted)]">Invalid reset link.</p>
      </div>
    );
  }

  if (success) {
    return (
      <div className="flex min-h-screen items-center justify-center">
        <div className="rounded-xl border border-[var(--border)] bg-[var(--bg-card)] p-8 w-full max-w-sm space-y-4 text-center">
          <p className="text-sm text-green-500">Password reset successfully.</p>
          <a href="/login" className="text-sm text-[var(--accent)] hover:underline">
            Back to sign in
          </a>
        </div>
      </div>
    );
  }

  return (
    <div className="flex min-h-screen items-center justify-center">
      <div className="rounded-xl border border-[var(--border)] bg-[var(--bg-card)] p-8 w-full max-w-sm space-y-6">
        <div className="space-y-1">
          <h1 className="text-xl font-bold text-[var(--accent)]">Atma Finances</h1>
          <p className="text-sm text-[var(--text-muted)]">Set new password</p>
        </div>

        {error && <p className="text-sm text-red-500">{error}</p>}

        <form onSubmit={handleSubmit} className="space-y-4">
          <input
            type="password"
            placeholder="New password"
            value={password}
            onChange={(event) => setPassword(event.target.value)}
            required
            minLength={8}
            className="w-full rounded-lg border border-[var(--border)] bg-transparent px-3 py-2 text-sm"
          />
          <input
            type="password"
            placeholder="Confirm password"
            value={confirmPassword}
            onChange={(event) => setConfirmPassword(event.target.value)}
            required
            minLength={8}
            className="w-full rounded-lg border border-[var(--border)] bg-transparent px-3 py-2 text-sm"
          />
          <button
            type="submit"
            disabled={loading}
            className="w-full rounded-lg bg-[var(--accent)] px-4 py-2.5 text-sm font-medium text-white transition-opacity hover:opacity-90 disabled:opacity-50"
          >
            {loading ? "..." : "Reset Password"}
          </button>
        </form>
      </div>
    </div>
  );
}

// src/routes/(auth)/reset-password/+page.svelte
<script lang="ts">
  import { page } from "$app/stores";
  import Button from "$lib/components/ui/button.svelte";
  import Input from "$lib/components/ui/input.svelte";

  $: token = $page.url.searchParams.get("token") ?? "";
  let password = "";
  let confirmPassword = "";
  let error = "";
  let success = false;
  let loading = false;

  async function handleSubmit() {
    error = "";

    if (password !== confirmPassword) {
      error = "Passwords do not match";
      return;
    }

    loading = true;
    try {
      const res = await fetch("/api/auth/reset-password", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ token, password }),
      });
      if (!res.ok) {
        const payload = await res.json().catch(() => ({}));
        error = payload?.message ?? "Something went wrong. Please try again.";
        return;
      }
      success = true;
    } finally {
      loading = false;
    }
  }
</script>

<div class="flex min-h-screen items-center justify-center">
  {#if !token}
    <div class="text-(--text-muted)">Invalid reset link.</div>
  {:else if success}
    <div class="w-full max-w-sm space-y-4 rounded-xl border border-(--border) bg-(--bg-card) p-8 text-center">
      <p class="text-sm text-green-500">Password reset successfully.</p>
      <a href="/login" class="text-sm text-(--accent) hover:underline">Back to sign in</a>
    </div>
  {:else}
    <div class="w-full max-w-sm space-y-6 rounded-xl border border-(--border) bg-(--bg-card) p-8">
      <div class="space-y-1">
        <h1 class="text-xl font-bold text-(--accent)">Atma Finances</h1>
        <p class="text-sm text-(--text-muted)">Set new password</p>
      </div>

      {#if error}
        <p class="text-sm text-red-500">{error}</p>
      {/if}

      <form class="space-y-4" on:submit|preventDefault={handleSubmit}>
        <Input bind:value={password} type="password" placeholder="New password" required minlength="8" />
        <Input bind:value={confirmPassword} type="password" placeholder="Confirm password" required minlength="8" />
        <Button type="submit" className="w-full" disabled={loading}>{loading ? "..." : "Reset Password"}</Button>
      </form>
    </div>
  {/if}
</div>
