// pages/login.vue
<script setup lang="ts">
definePageMeta({ layout: "blank" });

type Mode = "login" | "register" | "forgot-password";

const mode = ref<Mode>("login");
const email = ref("");
const password = ref("");
const name = ref("");
const error = ref("");
const success = ref("");
const loading = ref(false);

const title = computed(() =>
  mode.value === "login" ? "Sign In" : mode.value === "register" ? "Create Account" : "Reset Password",
);

async function handleSubmit() {
  error.value = "";
  success.value = "";
  loading.value = true;

  try {
    if (mode.value === "login") {
      await $fetch("/api/auth/login", {
        method: "POST",
        body: { email: email.value, password: password.value },
      });
      await sessionFetch();
      await navigateTo("/");
    } else if (mode.value === "register") {
      await $fetch("/api/auth/register", {
        method: "POST",
        body: { email: email.value, password: password.value, name: name.value },
      });
      await $fetch("/api/auth/login", {
        method: "POST",
        body: { email: email.value, password: password.value },
      });
      await sessionFetch();
      await navigateTo("/");
    } else {
      await $fetch("/api/auth/forgot-password", {
        method: "POST",
        body: { email: email.value },
      });
      success.value = "If that email exists, a reset link has been sent.";
    }
  } catch (e) {
    if (mode.value === "login") error.value = "Invalid email or password";
    else if (mode.value === "register")
      error.value = (e as { data?: { message?: string } })?.data?.message ?? "Registration failed";
    else error.value = "Something went wrong. Please try again.";
  } finally {
    loading.value = false;
  }
}

function switchMode(newMode: Mode) {
  mode.value = newMode;
  error.value = "";
  success.value = "";
}

const { fetch: sessionFetch } = useUserSession();
</script>

<template>
  <div
    class="flex min-h-screen items-center justify-center"
    style="background: linear-gradient(135deg, #f0f4ff 0%, #f8f9fb 50%, #fdf2f8 100%)"
  >
    <div
      class="rounded-2xl bg-[var(--bg-card)] p-8 w-full max-w-sm space-y-6"
      style="box-shadow: 0 4px 24px rgba(0, 0, 0, 0.08)"
    >
      <div class="space-y-1">
        <h1 class="text-xl font-bold text-[var(--accent)]">Atma Finances</h1>
        <p class="text-sm text-[var(--text-muted)]">{{ title }}</p>
      </div>

      <p v-if="error" class="rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700">{{ error }}</p>
      <p v-if="success" class="rounded-lg bg-green-50 px-3 py-2 text-sm text-green-700">{{ success }}</p>

      <form class="space-y-4" @submit.prevent="handleSubmit">
        <input
          v-if="mode === 'register'"
          v-model="name"
          type="text"
          placeholder="Name"
          class="w-full rounded-lg border border-[var(--border)] bg-[var(--bg)] px-3 py-2.5 text-sm transition-colors focus:border-[var(--accent)] focus:outline-none focus:ring-2 focus:ring-[var(--accent)]/20"
        />
        <input
          v-model="email"
          type="email"
          placeholder="Email"
          required
          class="w-full rounded-lg border border-[var(--border)] bg-[var(--bg)] px-3 py-2.5 text-sm transition-colors focus:border-[var(--accent)] focus:outline-none focus:ring-2 focus:ring-[var(--accent)]/20"
        />
        <input
          v-if="mode !== 'forgot-password'"
          v-model="password"
          type="password"
          placeholder="Password"
          required
          minlength="8"
          class="w-full rounded-lg border border-[var(--border)] bg-[var(--bg)] px-3 py-2.5 text-sm transition-colors focus:border-[var(--accent)] focus:outline-none focus:ring-2 focus:ring-[var(--accent)]/20"
        />
        <button
          type="submit"
          :disabled="loading"
          class="w-full rounded-lg bg-[var(--accent)] px-4 py-2.5 text-sm font-medium text-white transition-colors hover:bg-[var(--accent-hover)] disabled:opacity-50"
        >
          {{ loading ? "..." : title }}
        </button>
      </form>

      <template v-if="mode === 'login'">
        <div class="relative">
          <div class="absolute inset-0 flex items-center">
            <div class="w-full border-t border-[var(--border)]" />
          </div>
          <div class="relative flex justify-center text-xs">
            <span class="bg-[var(--bg-card)] px-2 text-[var(--text-muted)]">or</span>
          </div>
        </div>
        <a
          href="/auth/google"
          class="block w-full rounded-lg border border-[var(--border)] bg-[var(--bg)] px-4 py-2.5 text-center text-sm font-medium transition-colors hover:bg-[var(--bg-card-hover)]"
        >
          Sign in with Google
        </a>
      </template>

      <div class="flex justify-between text-xs text-[var(--text-muted)]">
        <template v-if="mode === 'login'">
          <button type="button" class="hover:text-[var(--accent)] transition-colors" @click="switchMode('register')">
            Create account
          </button>
          <button
            type="button"
            class="hover:text-[var(--accent)] transition-colors"
            @click="switchMode('forgot-password')"
          >
            Forgot password?
          </button>
        </template>
        <button
          v-else
          type="button"
          class="hover:text-[var(--accent)] transition-colors"
          @click="switchMode('login')"
        >
          Back to sign in
        </button>
      </div>

      <div class="border-t border-[var(--border)] pt-4 text-center">
        <p class="text-xs text-[var(--text-muted)]">Want to browse without signing in?</p>
        <NuxtLink to="/" class="mt-1 inline-block text-sm font-medium text-[var(--accent)] hover:underline">
          Continue as guest
        </NuxtLink>
      </div>
    </div>
  </div>
</template>

// src/app/login/page.tsx
"use client";

import { signIn } from "next-auth/react";
import { useState } from "react";

type Mode = "login" | "register" | "forgot-password";

export default function LoginPage() {
  const [mode, setMode] = useState<Mode>("login");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [name, setName] = useState("");
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [loading, setLoading] = useState(false);

  async function handleSubmit(event: React.FormEvent) {
    event.preventDefault();
    setError("");
    setSuccess("");
    setLoading(true);

    try {
      if (mode === "login") {
        const result = await signIn("credentials", { email, password, redirect: false });
        if (result?.error) setError("Invalid email or password");
        else window.location.href = "/";
      } else if (mode === "register") {
        const response = await fetch("/api/auth/register", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ email, password, name }),
        });
        const data = await response.json();
        if (!response.ok) {
          setError(data.error);
        } else {
          const result = await signIn("credentials", { email, password, redirect: false });
          if (result?.error) setError("Registration succeeded but login failed. Please sign in.");
          else window.location.href = "/";
        }
      } else {
        const response = await fetch("/api/auth/forgot-password", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ email }),
        });
        if (response.ok) setSuccess("If that email exists, a reset link has been sent.");
        else setError("Something went wrong. Please try again.");
      }
    } catch {
      setError("Something went wrong. Please try again.");
    } finally {
      setLoading(false);
    }
  }

  const title = mode === "login" ? "Sign In" : mode === "register" ? "Create Account" : "Reset Password";

  return (
    <div
      className="flex min-h-screen items-center justify-center"
      style={{ background: "linear-gradient(135deg, #f0f4ff 0%, #f8f9fb 50%, #fdf2f8 100%)" }}
    >
      <div
        className="rounded-2xl bg-[var(--bg-card)] p-8 w-full max-w-sm space-y-6"
        style={{ boxShadow: "0 4px 24px rgba(0,0,0,0.08)" }}
      >
        <div className="space-y-1">
          <h1 className="text-xl font-bold text-[var(--accent)]">Atma Finances</h1>
          <p className="text-sm text-[var(--text-muted)]">{title}</p>
        </div>

        {error && <p className="rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}
        {success && <p className="rounded-lg bg-green-50 px-3 py-2 text-sm text-green-700">{success}</p>}

        <form onSubmit={handleSubmit} className="space-y-4">
          {mode === "register" && (
            <input
              type="text"
              placeholder="Name"
              value={name}
              onChange={(event) => setName(event.target.value)}
              className="w-full rounded-lg border border-[var(--border)] bg-[var(--bg)] px-3 py-2.5 text-sm transition-colors focus:border-[var(--accent)] focus:outline-none focus:ring-2 focus:ring-[var(--accent)]/20"
            />
          )}
          <input
            type="email"
            placeholder="Email"
            value={email}
            onChange={(event) => setEmail(event.target.value)}
            required
            className="w-full rounded-lg border border-[var(--border)] bg-[var(--bg)] px-3 py-2.5 text-sm transition-colors focus:border-[var(--accent)] focus:outline-none focus:ring-2 focus:ring-[var(--accent)]/20"
          />
          {mode !== "forgot-password" && (
            <input
              type="password"
              placeholder="Password"
              value={password}
              onChange={(event) => setPassword(event.target.value)}
              required
              minLength={8}
              className="w-full rounded-lg border border-[var(--border)] bg-[var(--bg)] px-3 py-2.5 text-sm transition-colors focus:border-[var(--accent)] focus:outline-none focus:ring-2 focus:ring-[var(--accent)]/20"
            />
          )}
          <button
            type="submit"
            disabled={loading}
            className="w-full rounded-lg bg-[var(--accent)] px-4 py-2.5 text-sm font-medium text-white transition-colors hover:bg-[var(--accent-hover)] disabled:opacity-50"
          >
            {loading ? "..." : title}
          </button>
        </form>

        {mode === "login" && (
          <>
            <div className="relative">
              <div className="absolute inset-0 flex items-center">
                <div className="w-full border-t border-[var(--border)]" />
              </div>
              <div className="relative flex justify-center text-xs">
                <span className="bg-[var(--bg-card)] px-2 text-[var(--text-muted)]">or</span>
              </div>
            </div>
            <button
              type="button"
              onClick={() => signIn("google", { callbackUrl: "/" })}
              className="w-full rounded-lg border border-[var(--border)] bg-[var(--bg)] px-4 py-2.5 text-sm font-medium transition-colors hover:bg-[var(--bg-card-hover)]"
            >
              Sign in with Google
            </button>
          </>
        )}

        <div className="flex justify-between text-xs text-[var(--text-muted)]">
          {mode === "login" && (
            <>
              <button
                type="button"
                onClick={() => setMode("register")}
                className="hover:text-[var(--accent)] transition-colors"
              >
                Create account
              </button>
              <button
                type="button"
                onClick={() => setMode("forgot-password")}
                className="hover:text-[var(--accent)] transition-colors"
              >
                Forgot password?
              </button>
            </>
          )}
          {mode !== "login" && (
            <button
              type="button"
              onClick={() => {
                setMode("login");
                setError("");
                setSuccess("");
              }}
              className="hover:text-[var(--accent)] transition-colors"
            >
              Back to sign in
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
