// src/lib/components/AppNav.svelte
<script lang="ts">
  import { page } from "$app/stores";
  import { goto, invalidateAll } from "$app/navigation";
  import Button from "$lib/components/ui/button.svelte";
  import type { SessionUser } from "$lib/types";

  export let user: SessionUser | null = null;

  const links = [
    { href: "/", label: "Overview" },
    { href: "/transactions", label: "Transactions" },
  ];

  $: navLinks = user?.isSuperAdmin ? [...links, { href: "/admin", label: "Admin" }] : links;

  async function signOut() {
    await fetch("/api/auth/logout", { method: "POST" });
    await invalidateAll();
    await goto("/login");
  }
</script>

<nav class="bg-(--bg-card)" style="box-shadow: 0 1px 3px rgba(0, 0, 0, 0.05)">
  <div class="mx-auto flex max-w-7xl items-center gap-8 px-4 py-3 sm:px-6 lg:px-8">
    <a href="/" class="text-lg font-bold tracking-tight text-(--accent)">Atma Finances</a>
    <div class="flex flex-1 gap-1">
      {#each navLinks as link}
        <a
          href={link.href}
          class={
            $page.url.pathname === link.href
              ? "rounded-lg bg-(--accent-light) px-3 py-1.5 text-sm font-medium text-(--accent)"
              : "rounded-lg px-3 py-1.5 text-sm font-medium text-(--text-muted) transition-colors hover:bg-(--bg-card-hover) hover:text-(--text)"
          }
        >
          {link.label}
        </a>
      {/each}
    </div>
    <div class="flex items-center gap-3">
      {#if user}
        {#if user.image}
          <img
            src={user.image}
            alt={user.name ?? ""}
            width="32"
            height="32"
            referrerpolicy="no-referrer"
            class="rounded-full ring-2 ring-(--border)"
          />
        {/if}
        <span class="text-sm font-medium text-(--text)">{user.name ?? user.email}</span>
        <Button variant="ghost" className="h-8 px-3" on:click={signOut}>Sign out</Button>
      {:else}
        <a href="/login">
          <Button>Sign in</Button>
        </a>
      {/if}
    </div>
  </div>
</nav>

// components/AppNav.vue
<script setup lang="ts">
const { loggedIn, user, clear } = useUserSession();
const route = useRoute();

const links = [
  { href: "/", label: "Overview" },
  { href: "/transactions", label: "Transactions" },
];

const navLinks = computed(() => {
  if (user.value?.isSuperAdmin) return [...links, { href: "/admin", label: "Admin" }];
  return links;
});

async function signOut() {
  await clear();
  await navigateTo("/login");
}
</script>

<template>
  <nav class="bg-[var(--bg-card)]" style="box-shadow: 0 1px 3px rgba(0, 0, 0, 0.05)">
    <div class="mx-auto flex max-w-7xl items-center gap-8 px-4 py-3 sm:px-6 lg:px-8">
      <NuxtLink to="/" class="text-lg font-bold tracking-tight text-[var(--accent)]">Atma Finances</NuxtLink>
      <div class="flex flex-1 gap-1">
        <NuxtLink
          v-for="link in navLinks"
          :key="link.href"
          :to="link.href"
          :class="[
            'rounded-lg px-3 py-1.5 text-sm font-medium transition-colors',
            route.path === link.href
              ? 'bg-[var(--accent-light)] text-[var(--accent)]'
              : 'text-[var(--text-muted)] hover:text-[var(--text)] hover:bg-[var(--bg-card-hover)]',
          ]"
        >
          {{ link.label }}
        </NuxtLink>
      </div>
      <div class="flex items-center gap-3">
        <template v-if="loggedIn">
          <img
            v-if="user?.image"
            :src="user.image"
            :alt="user.name ?? ''"
            width="32"
            height="32"
            referrerpolicy="no-referrer"
            class="rounded-full ring-2 ring-[var(--border)]"
          />
          <span class="text-sm font-medium text-[var(--text)]">{{ user?.name }}</span>
          <button
            type="button"
            class="rounded-lg px-3 py-1.5 text-sm text-[var(--text-muted)] transition-colors hover:text-[var(--text)] hover:bg-[var(--bg-card-hover)]"
            @click="signOut"
          >
            Sign out
          </button>
        </template>
        <NuxtLink
          v-else
          to="/login"
          class="rounded-lg bg-[var(--accent)] px-4 py-1.5 text-sm font-medium text-white transition-colors hover:bg-[var(--accent-hover)]"
        >
          Sign in
        </NuxtLink>
      </div>
    </div>
  </nav>
</template>
