// src/lib/components/SummaryCard.svelte
<script lang="ts">
  export let label: string;
  export let value: number;
  export let color: string;
  export let bg: string;
</script>

<div class="rounded-xl p-5" style={`background: ${bg}; box-shadow: var(--shadow-sm);`}>
  <p class="text-xs font-medium text-(--text-muted)">{label}</p>
  <p class="mt-2 text-2xl font-bold" style={`color: ${color};`}>${value.toLocaleString()}</p>
</div>

// components/SummaryCard.vue
<script setup lang="ts">
defineProps<{
  label: string;
  value: number;
  color: string;
  bg: string;
}>();
</script>

<template>
  <div class="rounded-xl p-5" :style="{ background: bg, boxShadow: 'var(--shadow-sm)' }">
    <p class="text-xs font-medium text-[var(--text-muted)]">{{ label }}</p>
    <p class="mt-2 text-2xl font-bold" :style="{ color }">${{ value.toLocaleString() }}</p>
  </div>
</template>
