// src/routes/admin/+page.svelte
<script lang="ts">
  import { invalidateAll } from "$app/navigation";
  import Input from "$lib/components/ui/input.svelte";
  import Button from "$lib/components/ui/button.svelte";
  import Card from "$lib/components/ui/card.svelte";
  import CardHeader from "$lib/components/ui/card-header.svelte";
  import CardContent from "$lib/components/ui/card-content.svelte";
  import CardTitle from "$lib/components/ui/card-title.svelte";
  import Table from "$lib/components/ui/table.svelte";
  import TableHeader from "$lib/components/ui/table-header.svelte";
  import TableBody from "$lib/components/ui/table-body.svelte";
  import TableRow from "$lib/components/ui/table-row.svelte";
  import TableHead from "$lib/components/ui/table-head.svelte";
  import TableCell from "$lib/components/ui/table-cell.svelte";

  export let data: { data: { admins: { id: string; email: string; name: string | null }[]; superAdminEmails: string[] } };
  const payload = data.data;

  let email = "";
  let loading = false;
  let error = "";

  async function addAdmin(event: Event) {
    event.preventDefault();
    if (!email.trim()) return;

    loading = true;
    error = "";

    try {
      const res = await fetch("/api/admin", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ email: email.trim() }),
      });
      if (!res.ok) {
        const payload = await res.json().catch(() => ({}));
        throw new Error(payload?.message || "Failed to add admin");
      }
      email = "";
      await invalidateAll();
    } catch (e) {
      error = (e as Error).message || "Failed to add admin";
    } finally {
      loading = false;
    }
  }

  async function removeAdmin(adminEmail: string) {
    loading = true;
    error = "";

    try {
      const res = await fetch("/api/admin", {
        method: "DELETE",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ email: adminEmail }),
      });
      if (!res.ok) {
        const payload = await res.json().catch(() => ({}));
        throw new Error(payload?.message || "Failed to remove admin");
      }
      await invalidateAll();
    } catch (e) {
      error = (e as Error).message || "Failed to remove admin";
    } finally {
      loading = false;
    }
  }
</script>

<div class="space-y-6">
  <h1 class="text-2xl font-bold">Admin Management</h1>
  <Card className="border border-(--border)">
    <CardHeader>
      <CardTitle>Current Admins</CardTitle>
    </CardHeader>
    <CardContent>
      <Table>
        <TableHeader>
          <TableRow className="border-b border-(--border) hover:bg-transparent">
            <TableHead>Email</TableHead>
            <TableHead>Name</TableHead>
            <TableHead className="text-right">Actions</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {#each payload.admins as admin (admin.id)}
            <TableRow>
              <TableCell className="px-4 py-2 text-sm">
                {admin.email}
                {#if payload.superAdminEmails.includes(admin.email)}
                  <span class="ml-2 text-xs text-(--accent)">(Super Admin)</span>
                {/if}
              </TableCell>
              <TableCell className="px-4 py-2 text-sm text-(--text-muted)">{admin.name ?? "—"}</TableCell>
              <TableCell className="px-4 py-2 text-right">
                {#if !payload.superAdminEmails.includes(admin.email)}
                  <Button
                    variant="ghost"
                    size="sm"
                    className="text-(--red)"
                    on:click={() => removeAdmin(admin.email)}
                    disabled={loading}
                  >
                    Remove
                  </Button>
                {/if}
              </TableCell>
            </TableRow>
          {/each}
        </TableBody>
      </Table>

      <form class="mt-4 flex items-end gap-3" on:submit={addAdmin}>
        <div class="flex-1">
          <label for="admin-email" class="mb-1 block text-xs font-medium text-(--text-muted)">
            Add admin by email
          </label>
          <Input id="admin-email" bind:value={email} type="email" placeholder="user@example.com" />
        </div>
        <Button type="submit" disabled={loading || !email.trim()}>Add</Button>
      </form>

      {#if error}
        <p class="mt-3 text-sm text-(--red)">{error}</p>
      {/if}
    </CardContent>
  </Card>
</div>

// pages/admin.vue
<script setup lang="ts">
const { user } = useUserSession();

if (!user.value?.isSuperAdmin) await navigateTo("/");

const { data, refresh } = await useFetch("/api/admin");

const email = ref("");
const loading = ref(false);
const error = ref("");

async function addAdmin(event: Event) {
  event.preventDefault();
  if (!email.value.trim()) return;

  loading.value = true;
  error.value = "";

  try {
    const response = await $fetch("/api/admin", {
      method: "POST",
      body: { email: email.value.trim() },
    });
    if (response) {
      email.value = "";
      await refresh();
    }
  } catch (e) {
    error.value = (e as { data?: { message?: string } })?.data?.message ?? "Failed to add admin";
  } finally {
    loading.value = false;
  }
}

async function removeAdmin(adminEmail: string) {
  loading.value = true;
  error.value = "";

  try {
    await $fetch("/api/admin", {
      method: "DELETE",
      body: { email: adminEmail },
    });
    await refresh();
  } catch (e) {
    error.value = (e as { data?: { message?: string } })?.data?.message ?? "Failed to remove admin";
  } finally {
    loading.value = false;
  }
}
</script>

<template>
  <div class="space-y-6">
    <h1 class="text-2xl font-bold">Admin Management</h1>
    <div v-if="data" class="rounded-xl border border-[var(--border)] bg-[var(--bg-card)] p-6">
      <h2 class="mb-4 text-lg font-semibold">Current Admins</h2>

      <div class="space-y-4">
        <table class="w-full">
          <thead>
            <tr class="border-b border-[var(--border)]">
              <th class="px-4 py-3 text-left text-xs font-medium uppercase tracking-wider text-[var(--text-muted)]">
                Email
              </th>
              <th class="px-4 py-3 text-left text-xs font-medium uppercase tracking-wider text-[var(--text-muted)]">
                Name
              </th>
              <th class="px-4 py-3 text-right text-xs font-medium uppercase tracking-wider text-[var(--text-muted)]">
                Actions
              </th>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="admin in data.admins"
              :key="admin.id"
              class="border-b border-[var(--border)] hover:bg-[var(--bg-card-hover)] transition-colors"
            >
              <td class="px-4 py-2 text-sm">
                {{ admin.email }}
                <span v-if="data.superAdminEmails.includes(admin.email)" class="ml-2 text-xs text-[var(--accent)]">
                  (Super Admin)
                </span>
              </td>
              <td class="px-4 py-2 text-sm text-[var(--text-muted)]">{{ admin.name ?? "—" }}</td>
              <td class="px-4 py-2 text-right">
                <button
                  v-if="!data.superAdminEmails.includes(admin.email)"
                  type="button"
                  :disabled="loading"
                  class="rounded-md px-3 py-1 text-sm text-[var(--red)] transition-colors hover:bg-[var(--bg-card-hover)] disabled:opacity-50"
                  @click="removeAdmin(admin.email)"
                >
                  Remove
                </button>
              </td>
            </tr>
          </tbody>
        </table>

        <form class="flex gap-3 items-end" @submit.prevent="addAdmin">
          <div class="flex-1">
            <label for="admin-email" class="block text-xs font-medium text-[var(--text-muted)] mb-1">
              Add admin by email
            </label>
            <input
              id="admin-email"
              v-model="email"
              type="email"
              placeholder="user@example.com"
              class="w-full rounded-md border border-[var(--border)] bg-[var(--bg)] px-3 py-2 text-sm outline-none focus:border-[var(--accent)]"
            />
          </div>
          <button
            type="submit"
            :disabled="loading || !email.trim()"
            class="rounded-md bg-[var(--accent)] px-4 py-2 text-sm font-medium text-white transition-colors hover:opacity-90 disabled:opacity-50"
          >
            Add
          </button>
        </form>

        <p v-if="error" class="text-sm text-[var(--red)]">{{ error }}</p>
      </div>
    </div>
  </div>
</template>
