// src/routes/transactions/+page.svelte
<script lang="ts">
  import TransactionsTable from "$lib/components/TransactionsTable.svelte";

  export let data: { data: any };
  const payload = data.data;
</script>

{#if payload}
  <div class="space-y-6">
    <h1 class="text-2xl font-bold">Transactions</h1>
    <TransactionsTable
      transactions={payload.transactions}
      highlightPersonIds={payload.highlightPersonIds}
      maskedPersonIds={payload.maskedPersonIds}
    />
  </div>
{/if}

// src/app/transactions/page.tsx
import { getCachedTransactions } from "@/lib/data";
import { TransactionsTable } from "@/components/transactions-table";

export default async function TransactionsPage() {
  const transactions = await getCachedTransactions();

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold">Transactions</h1>
      <TransactionsTable transactions={transactions} />
    </div>
  );
}
